### PR TITLE
refactor: errors variable

### PR DESCRIPTION
**Pull request by arthurgustin**
Hi,
Just exposed error message to be able to do assertion in my program with `errors.Cause(...)`

### CODE REVIEW

**Comment by terminalstatic** [comment]
From my point of view I don't see benefits and this would also introduce an external dependency ...
You could easily wrap the returned errors in your code if you need typed errors ... 

I should probably work over some of the error strings though ...

**Comment by arthurgustin** [comment]
I understand,
This is not yet integrated in my program so for now I don't really need this feature, but I will in a couple of weeks. This solution is better than doing string matching in my side...
Actually I need to retrieve the locator of the error (the name node), the line (if possible) and the message in order to tell the user why his xml request is wrong. What is your point of view ?

btw thank you a lot for this lib

**Comment by terminalstatic** [comment]
No worries.

Could be doable, [see here](http://xmlsoft.org/html/libxml-xmlerror.html#xmlError) 
It's not granted if everything in this struct is valid info though (I think I have already played around with it a bit)...
Where exactly do you need this info? Parsing or validating?

**Comment by arthurgustin** [comment]
I need this for validation. In fact I have a validation step before doing anything else, so ye..

**Comment by terminalstatic** [comment]
I'll look into it and keep you posted.

**Comment by terminalstatic** [comment]
It's now possible to access ValidationError fields via type assertion.
As I had to come up with  an error type for this anyway I typed the other errors aswell.
Might come in handy if I need to do stuff to the parsing errors in the future ...
Hope those changes provide useful.

**Comment by arthurgustin** [comment]
Hi, just had to fix a few tests, and now everything is fine. Your library allowed me to be 0.5s faster on my requests and I am now under the SLA of 1 second which is the requirement of my company.
Thank you a lot for that.

**Comment by terminalstatic** [comment]
:thumbsup:
My pleasure.

**Pull request closed without merging**
